# Generated by Django 3.0.7 on 2020-06-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imgpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMGPost',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
