# Generated by Django 3.0.7 on 2020-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='button_url',
            field=models.CharField(default='hell', max_length=200),
            preserve_default=False,
        ),
    ]
